/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#![allow(unused_extern_crates)]
#![cfg_attr(feature = "crown", feature(register_tool))]
#![cfg_attr(feature = "crown", register_tool(crown))]
#![cfg_attr(feature = "oom_with_hook", feature(alloc_error_hook))]

// These extern crates are needed for linking
extern crate encoding_c;
extern crate encoding_c_mem;
#[cfg(feature = "intl")]
extern crate icu_capi;
#[cfg(feature = "libz-rs")]
extern crate libz_rs_sys;
#[cfg(feature = "libz-sys")]
extern crate libz_sys;

// The jsimpls module just implements traits so can be private
mod jsimpls;

// Modules with public definitions
pub mod glue;
pub mod jsgc;
pub mod jsid;
pub mod jsval;
pub mod trace;

// Reexport the bindings in the jsapi module
pub use crate::generated::root as jsapi;

// The bindings generated by bindgen
#[doc(hidden)]
#[allow(dead_code)]
mod generated {
    #![allow(unnecessary_transmutes)]
    include!(concat!(env!("OUT_DIR"), "/build/jsapi.rs"));
}

/*fn panic_hook(info: &std::panic::PanicInfo) {
    eprint!("Panic from mozjs: {}", info);
}*/

/// Configure a panic hook to redirect rust panics to MFBT's MOZ_Crash.
/// See <https://searchfox.org/mozilla-esr115/source/mozglue/static/rust/lib.rs#106>
#[no_mangle]
pub extern "C" fn install_rust_hooks() {
    //std::panic::set_hook(Box::new(panic_hook));
    #[cfg(feature = "oom_with_hook")]
    oom_hook::install();
}

#[cfg(feature = "oom_with_hook")]
mod oom_hook {
    use std::alloc::{set_alloc_error_hook, Layout};

    extern "C" {
        pub fn RustHandleOOM(size: usize) -> !;
    }

    pub fn hook(layout: Layout) {
        unsafe {
            RustHandleOOM(layout.size());
        }
    }

    pub fn install() {
        set_alloc_error_hook(hook);
    }
}

/// Default allocator bridge: routes SpiderMonkey C++ allocations to libc.
///
/// Enable the `custom-allocator` feature to suppress these defaults.
/// When that feature is active, the consumer crate must provide
/// `#[no_mangle] pub unsafe extern "C"` definitions for:
///   - `mozjs_sys_malloc`
///   - `mozjs_sys_calloc`
///   - `mozjs_sys_realloc`
///   - `mozjs_sys_free`
///   - `mozjs_sys_memalign`
///   - `mozjs_sys_malloc_usable_size`
#[cfg(not(feature = "custom-allocator"))]
mod alloc_bridge {
    use std::os::raw::c_void;

    #[no_mangle]
    pub unsafe extern "C" fn mozjs_sys_malloc(size: usize) -> *mut c_void {
        libc::malloc(size)
    }

    #[no_mangle]
    pub unsafe extern "C" fn mozjs_sys_calloc(n: usize, size: usize) -> *mut c_void {
        libc::calloc(n, size)
    }

    #[no_mangle]
    pub unsafe extern "C" fn mozjs_sys_realloc(p: *mut c_void, size: usize) -> *mut c_void {
        libc::realloc(p, size)
    }

    #[no_mangle]
    pub unsafe extern "C" fn mozjs_sys_free(p: *mut c_void) {
        libc::free(p)
    }

    #[no_mangle]
    pub unsafe extern "C" fn mozjs_sys_memalign(align: usize, size: usize) -> *mut c_void {
        #[cfg(target_os = "windows")]
        {
            libc::_aligned_malloc(size, align)
        }
        #[cfg(not(target_os = "windows"))]
        {
            let mut ptr: *mut c_void = std::ptr::null_mut();
            if libc::posix_memalign(&mut ptr, align, size) == 0 {
                ptr
            } else {
                std::ptr::null_mut()
            }
        }
    }

    #[no_mangle]
    pub unsafe extern "C" fn mozjs_sys_malloc_usable_size(p: *const c_void) -> usize {
        #[cfg(target_vendor = "apple")]
        {
            libc::malloc_size(p)
        }
        #[cfg(target_os = "windows")]
        {
            libc::_msize(p as *mut c_void)
        }
        #[cfg(not(any(target_vendor = "apple", target_os = "windows")))]
        {
            libc::malloc_usable_size(p as *mut c_void)
        }
    }
}
